name: Run Newman Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Newman
      run: npm install -g newman@latest

    - name: Install Reporter
      run: npm install -g newman-reporter-htmlextra@latest

    - name: Run Postman Collection
      run: newman run Mincom.gov.az_2.postman_collection.json -e Mincom.postman_environment.json -r htmlextra, cli

    - name: List newman directory (debugging step)
      run: ls -la newman

    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: newman-report
        path: newman/*.html

    - name: List newman directory (debugging step)
      run: ls -la newman
